%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.8 on {{2015,9,25},{6,8,49}}

-ifndef(ql2).
-define(ql2, true).

-define(ql2_gpb_version, "3.18.8").

-record('VersionDummy',
        {
        }).

-record('Query.AssocPair',
        {key,                           % = 1, string (optional)
         val                            % = 2, {msg,'Term'} (optional)
        }).

-record('Query',
        {type,                          % = 1, {enum,'Query.QueryType'} (optional)
         query,                         % = 2, {msg,'Term'} (optional)
         token,                         % = 3, int64 (optional)
         'OBSOLETE_noreply' = false,    % = 4, bool (optional)
         accepts_r_json = false,        % = 5, bool (optional)
         global_optargs = []            % = 6, [{msg,'Query.AssocPair'}]
        }).

-record('Frame',
        {type,                          % = 1, {enum,'Frame.FrameType'} (optional)
         pos,                           % = 2, int64 (optional)
         opt                            % = 3, string (optional)
        }).

-record('Backtrace',
        {frames = []                    % = 1, [{msg,'Frame'}]
        }).

-record('Response',
        {type,                          % = 1, {enum,'Response.ResponseType'} (optional)
         notes = [],                    % = 6, [{enum,'Response.ResponseNote'}]
         token,                         % = 2, int64 (optional)
         response = [],                 % = 3, [{msg,'Datum'}]
         backtrace,                     % = 4, {msg,'Backtrace'} (optional)
         profile                        % = 5, {msg,'Datum'} (optional)
        }).

-record('Datum.AssocPair',
        {key,                           % = 1, string (optional)
         val                            % = 2, {msg,'Datum'} (optional)
        }).

-record('Datum',
        {type,                          % = 1, {enum,'Datum.DatumType'} (optional)
         r_bool,                        % = 2, bool (optional)
         r_num,                         % = 3, double (optional)
         r_str,                         % = 4, string (optional)
         r_array = [],                  % = 5, [{msg,'Datum'}]
         r_object = []                  % = 6, [{msg,'Datum.AssocPair'}]
        }).

-record('Term.AssocPair',
        {key,                           % = 1, string (optional)
         val                            % = 2, {msg,'Term'} (optional)
        }).

-record('Term',
        {type,                          % = 1, {enum,'Term.TermType'} (optional)
         datum,                         % = 2, {msg,'Datum'} (optional)
         args = [],                     % = 3, [{msg,'Term'}]
         optargs = []                   % = 4, [{msg,'Term.AssocPair'}]
        }).

-endif.
