%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.25.2

-ifndef(ql2).
-define(ql2, true).

-define(ql2_gpb_version, "3.25.2").

-ifndef('VERSIONDUMMY_PB_H').
-define('VERSIONDUMMY_PB_H', true).
-record('VersionDummy',
        {
        }).
-endif.

-ifndef('QUERY.ASSOCPAIR_PB_H').
-define('QUERY.ASSOCPAIR_PB_H', true).
-record('Query.AssocPair',
        {key,                           % = 1, string (optional)
         val                            % = 2, {msg,'Term'} (optional)
        }).
-endif.

-ifndef('QUERY_PB_H').
-define('QUERY_PB_H', true).
-record('Query',
        {type,                          % = 1, {enum,'Query.QueryType'} (optional)
         query,                         % = 2, {msg,'Term'} (optional)
         token,                         % = 3, int64 (optional)
         'OBSOLETE_noreply' = false,    % = 4, bool (optional)
         accepts_r_json = false,        % = 5, bool (optional)
         global_optargs = []            % = 6, [{msg,'Query.AssocPair'}]
        }).
-endif.

-ifndef('FRAME_PB_H').
-define('FRAME_PB_H', true).
-record('Frame',
        {type,                          % = 1, {enum,'Frame.FrameType'} (optional)
         pos,                           % = 2, int64 (optional)
         opt                            % = 3, string (optional)
        }).
-endif.

-ifndef('BACKTRACE_PB_H').
-define('BACKTRACE_PB_H', true).
-record('Backtrace',
        {frames = []                    % = 1, [{msg,'Frame'}]
        }).
-endif.

-ifndef('RESPONSE_PB_H').
-define('RESPONSE_PB_H', true).
-record('Response',
        {type,                          % = 1, {enum,'Response.ResponseType'} (optional)
         error_type,                    % = 7, {enum,'Response.ErrorType'} (optional)
         notes = [],                    % = 6, [{enum,'Response.ResponseNote'}]
         token,                         % = 2, int64 (optional)
         response = [],                 % = 3, [{msg,'Datum'}]
         backtrace,                     % = 4, {msg,'Backtrace'} (optional)
         profile                        % = 5, {msg,'Datum'} (optional)
        }).
-endif.

-ifndef('DATUM.ASSOCPAIR_PB_H').
-define('DATUM.ASSOCPAIR_PB_H', true).
-record('Datum.AssocPair',
        {key,                           % = 1, string (optional)
         val                            % = 2, {msg,'Datum'} (optional)
        }).
-endif.

-ifndef('DATUM_PB_H').
-define('DATUM_PB_H', true).
-record('Datum',
        {type,                          % = 1, {enum,'Datum.DatumType'} (optional)
         r_bool,                        % = 2, bool (optional)
         r_num,                         % = 3, double (optional)
         r_str,                         % = 4, string (optional)
         r_array = [],                  % = 5, [{msg,'Datum'}]
         r_object = []                  % = 6, [{msg,'Datum.AssocPair'}]
        }).
-endif.

-ifndef('TERM.ASSOCPAIR_PB_H').
-define('TERM.ASSOCPAIR_PB_H', true).
-record('Term.AssocPair',
        {key,                           % = 1, string (optional)
         val                            % = 2, {msg,'Term'} (optional)
        }).
-endif.

-ifndef('TERM_PB_H').
-define('TERM_PB_H', true).
-record('Term',
        {type,                          % = 1, {enum,'Term.TermType'} (optional)
         datum,                         % = 2, {msg,'Datum'} (optional)
         args = [],                     % = 3, [{msg,'Term'}]
         optargs = []                   % = 4, [{msg,'Term.AssocPair'}]
        }).
-endif.

-endif.
